# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # compile the latex document
  build-latex:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # compile the document using texlive and latexmk
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: docs

    # Store the compiled pdf as an artifact
    - uses: actions/upload-artifact@v1
      with:
        name: documentation
        path: docs/main.pdf

  # run unit tests
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Perform unit tests
      uses: joergbrech/moxunit-action@master
      with:
        test_directory: tests
        src_directory: src
